version: '3.3'

services:
  ca-gateway:
    image: lnlscon/epics-ca-gateway:base-3.15-debian-9-test
    env_file:
      -  /storage/network-services/ca-gateway/lnls-ca-gateway.env
    deploy:
      replicas: 2
    networks: 
      - outside

networks:
  outside:
    external:
      name: "host"
